export const array= [
     {
        id:1,
        name:"Agra",
        info:"lorem ipsum dolor sit amet, consectetur adip",
        image:"taj.jpg",
        price:"69,999/-",
     },
     {
        id:2,
        name:"Agra",
        info:"lorem ipsum dolor sit amet, consectetur adip",
        image:"taj.jpg",
        price:"69,999/-",
     },
     {
        id:3,
        name:"Agra",
        info:"lorem ipsum dolor sit amet, consectetur adip",
        image:"taj.jpg",
        price:"69,999/-",
     },
     {
        id:4,
        name:"Agra",
        info:"lorem ipsum dolor sit amet, consectetur adip",
        image:"taj.jpg",
        price:"69,999/-",
     },
     {
        id:5,
        name:"Agra",
        info:"lorem ipsum dolor sit amet, consectetur adip",
        image:"taj.jpg",
        price:"69,999/-",
     },
     {
        id:6,
        name:"Agra",
        info:"lorem ipsum dolor sit amet, consectetur adip",
        image:"taj.jpg",
        price:"69,999/-",
     },
     {
      id:7,
      name:"Agra",
      info:"lorem ipsum dolor sit amet, consectetur adip",
      image:"taj.jpg",
      price:"69,999/-",
   },
];